-- CreateTable
CREATE TABLE `player_stats` (
    `id` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `totalGamesPlayed` INTEGER NOT NULL DEFAULT 0,
    `totalBattlesPlayed` INTEGER NOT NULL DEFAULT 0,
    `totalBattlesWon` INTEGER NOT NULL DEFAULT 0,
    `totalBattlesLost` INTEGER NOT NULL DEFAULT 0,
    `totalDungeonsCompleted` INTEGER NOT NULL DEFAULT 0,
    `simpleDungeonsCompleted` INTEGER NOT NULL DEFAULT 0,
    `smallDungeonsCompleted` INTEGER NOT NULL DEFAULT 0,
    `largeDungeonsCompleted` INTEGER NOT NULL DEFAULT 0,
    `totalClashes` INTEGER NOT NULL DEFAULT 0,
    `totalClashesWon` INTEGER NOT NULL DEFAULT 0,
    `totalClashesLost` INTEGER NOT NULL DEFAULT 0,
    `clashesWonByDamage` INTEGER NOT NULL DEFAULT 0,
    `clashesWonByType` INTEGER NOT NULL DEFAULT 0,
    `clashesLostByDefault` INTEGER NOT NULL DEFAULT 0,
    `totalDamageDealt` INTEGER NOT NULL DEFAULT 0,
    `totalDamageTaken` INTEGER NOT NULL DEFAULT 0,
    `highestDamageInClash` INTEGER NOT NULL DEFAULT 0,
    `totalHealthUsed` INTEGER NOT NULL DEFAULT 0,
    `fireCardWins` INTEGER NOT NULL DEFAULT 0,
    `waterCardWins` INTEGER NOT NULL DEFAULT 0,
    `earthCardWins` INTEGER NOT NULL DEFAULT 0,
    `airCardWins` INTEGER NOT NULL DEFAULT 0,
    `fireCardLosses` INTEGER NOT NULL DEFAULT 0,
    `waterCardLosses` INTEGER NOT NULL DEFAULT 0,
    `earthCardLosses` INTEGER NOT NULL DEFAULT 0,
    `airCardLosses` INTEGER NOT NULL DEFAULT 0,
    `totalCardsCollected` INTEGER NOT NULL DEFAULT 0,
    `totalCardUpgrades` INTEGER NOT NULL DEFAULT 0,
    `totalDamageUpgrades` INTEGER NOT NULL DEFAULT 0,
    `totalHealthUpgrades` INTEGER NOT NULL DEFAULT 0,
    `currentWinStreak` INTEGER NOT NULL DEFAULT 0,
    `longestWinStreak` INTEGER NOT NULL DEFAULT 0,
    `currentLoseStreak` INTEGER NOT NULL DEFAULT 0,
    `longestLoseStreak` INTEGER NOT NULL DEFAULT 0,
    `totalPlayTimeMinutes` INTEGER NOT NULL DEFAULT 0,
    `averageBattleTime` INTEGER NOT NULL DEFAULT 0,
    `fastestBattleWin` INTEGER NOT NULL DEFAULT 0,
    `totalDecksCreated` INTEGER NOT NULL DEFAULT 0,
    `mostUsedDeckId` VARCHAR(191) NULL,
    `totalEnvironmentsPlayed` INTEGER NOT NULL DEFAULT 0,

    UNIQUE INDEX `player_stats_userId_key`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `player_stats` ADD CONSTRAINT `player_stats_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
